CREATE TABLE IF NOT EXISTS `syarat_pendaftaran` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `jenjang` enum('PGIT-TKIT', 'SDIT', 'SMPIT', 'SMAIT', 'SLBIT') NOT NULL,
  `persyaratan_umum` text NOT NULL,
  `tahapan_seleksi` text NOT NULL,
  `biaya_pendaftaran` varchar(255) NOT NULL,
  `informasi_tambahan` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `jenjang` (`jenjang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert data awal
INSERT INTO `syarat_pendaftaran` (`jenjang`, `persyaratan_umum`, `tahapan_seleksi`, `biaya_pendaftaran`, `informasi_tambahan`) VALUES
('PGIT-TKIT', '<ol><li>Usia minimal 4 tahun untuk PGIT dan 5 tahun untuk TKIT per Juli tahun ajaran baru</li><li>Mengisi formulir pendaftaran secara online atau langsung di sekolah</li><li>Fotokopi akta kelahiran</li><li>Fotokopi Kartu Keluarga</li><li>Fotokopi KTP kedua orang tua</li><li>Pas foto berwarna ukuran 3x4 (4 lembar)</li></ol>', '<ol><li>Pendaftaran online atau langsung di sekolah</li><li>Wawancara orang tua</li><li>Observasi kesiapan anak</li><li>Pengumuman hasil seleksi</li><li>Pembayaran biaya masuk bagi yang diterima</li></ol>', 'Rp 300.000', 'Pendaftaran dibuka sepanjang tahun selama kuota masih tersedia'),
('SDIT', '<ol><li>Usia minimal 6 tahun per Juli tahun ajaran baru</li><li>Mengisi formulir pendaftaran secara online atau langsung di sekolah</li><li>Fotokopi akta kelahiran</li><li>Fotokopi Kartu Keluarga</li><li>Fotokopi KTP kedua orang tua</li><li>Pas foto berwarna ukuran 3x4 (4 lembar)</li><li>Fotokopi ijazah TK/PAUD (jika ada)</li></ol>', '<ol><li>Pendaftaran online atau langsung di sekolah</li><li>Tes kemampuan dasar (membaca, menulis, berhitung)</li><li>Tes kesiapan sekolah</li><li>Wawancara orang tua</li><li>Pengumuman hasil seleksi</li><li>Pembayaran biaya masuk bagi yang diterima</li></ol>', 'Rp 350.000', 'Prioritas diberikan kepada pendaftar yang melengkapi persyaratan lebih awal'),
('SMPIT', '<ol><li>Lulus SD/MI dengan usia maksimal 12 tahun</li><li>Mengisi formulir pendaftaran secara online atau langsung di sekolah</li><li>Fotokopi ijazah SD/MI dan SKHUN (dapat menyusul)</li><li>Fotokopi rapor kelas 4-6 SD/MI</li><li>Fotokopi akta kelahiran</li><li>Fotokopi Kartu Keluarga</li><li>Fotokopi KTP kedua orang tua</li><li>Pas foto berwarna ukuran 3x4 (4 lembar)</li><li>Surat keterangan berkelakuan baik dari sekolah asal</li></ol>', '<ol><li>Pendaftaran online atau langsung di sekolah</li><li>Tes akademik (Matematika, IPA, Bahasa Indonesia, Bahasa Inggris)</li><li>Tes kemampuan baca Al-Qur\'an</li><li>Tes wawancara siswa</li><li>Wawancara orang tua</li><li>Pengumuman hasil seleksi</li><li>Pembayaran biaya masuk bagi yang diterima</li></ol>', 'Rp 400.000', 'Seleksi dilakukan secara berkala setiap bulan'),
('SMAIT', '<ol><li>Lulus SMP/MTs dengan usia maksimal 15 tahun</li><li>Mengisi formulir pendaftaran secara online atau langsung di sekolah</li><li>Fotokopi ijazah SMP/MTs dan SKHUN (dapat menyusul)</li><li>Fotokopi rapor kelas 7-9 SMP/MTs</li><li>Fotokopi akta kelahiran</li><li>Fotokopi Kartu Keluarga</li><li>Fotokopi KTP kedua orang tua</li><li>Pas foto berwarna ukuran 3x4 (4 lembar)</li><li>Surat keterangan berkelakuan baik dari sekolah asal</li></ol>', '<ol><li>Pendaftaran online atau langsung di sekolah</li><li>Tes akademik (Matematika, IPA, Bahasa Indonesia, Bahasa Inggris)</li><li>Tes kemampuan baca Al-Qur\'an dan pengetahuan keislaman</li><li>Tes wawancara siswa</li><li>Wawancara orang tua</li><li>Pengumuman hasil seleksi</li><li>Pembayaran biaya masuk bagi yang diterima</li></ol>', 'Rp 450.000', 'Biaya pendaftaran tidak dapat dikembalikan'),
('SLBIT', '<ol><li>Anak berkebutuhan khusus dengan usia 5-18 tahun</li><li>Mengisi formulir pendaftaran secara online atau langsung di sekolah</li><li>Fotokopi akta kelahiran</li><li>Fotokopi Kartu Keluarga</li><li>Fotokopi KTP kedua orang tua</li><li>Pas foto berwarna ukuran 3x4 (4 lembar)</li><li>Hasil diagnosa dari psikolog/dokter terkait kondisi anak</li><li>Riwayat perkembangan anak dan riwayat kesehatan</li><li>Fotokopi rapor sekolah sebelumnya (jika ada)</li></ol>', '<ol><li>Pendaftaran online atau langsung di sekolah</li><li>Observasi awal kemampuan anak</li><li>Wawancara mendalam dengan orang tua</li><li>Asesmen oleh tim ahli (psikolog, terapis, guru pendidikan khusus)</li><li>Penentuan program pendidikan yang sesuai</li><li>Pengumuman hasil seleksi</li><li>Pembayaran biaya masuk bagi yang diterima</li></ol>', 'Rp 500.000', 'Untuk informasi lebih lanjut, silakan hubungi kantor pendaftaran di (0721) 123456 atau email ke pendaftaran@baituljannahislamicschool.ac.id');