-- Add new columns to users table for profile settings
ALTER TABLE users
ADD COLUMN IF NOT EXISTS firstName VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS lastName VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS avatar VARCHAR(255) DEFAULT NULL;